version: "3.9"

services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret123
      - MYSQL_DATABASE=lcm_poc_v1
  payment-dummy:
    image: mockoon/cli:latest
    ports:
      - "3000:3000"
    command: -d https://raw.githubusercontent.com/yauritux/paymentlcmule/master/payment-dummy.json -i 0 -p 3000

